Signup Route
GSG-G13/Petopia pull request #20
Opened 2023-06-12 19:45 UTC by AbdallahAbujazar

Change fields names in User Model like full_name to fullName Relates #18

2023-06-13 10:45 UTC, Mu7ammadAbed requested changes

2023-06-13 10:45 UTC, Mu7ammadAbed commented on src/controllers/auth/signup.ts
> +    await validateSignup(req.body)
```suggestion
    }: IUser = await validateSignup(req.body)
```

2023-06-13 10:45 UTC, Mu7ammadAbed commented on src/controllers/auth/signup.ts
> +import { type IUser } from '../../interfaces/models'
```suggestion
import { type IUser } from '../../interfaces/fakeDataTypes'
```

2023-06-13 10:45 UTC, Mu7ammadAbed commented on src/validation/auth/signup.ts
> +import { type IUser } from '../../interfaces/models'
```suggestion
import { type User as IUser } from '../../interfaces/fakeDataTypes'
```

2023-06-13 10:45 UTC, Mu7ammadAbed commented on src/validation/auth/signup.ts
> +  await schema.validate(data, { abortEarly: false })
```suggestion
  const result = await schema.validate(data, { abortEarly: false })
  return result
```

2023-06-13 10:45 UTC, Mu7ammadAbed commented on src/queries/user/signup.ts
> +}
```suggestion
interface CreateUserProps {
  fullName: string
  email: string
  password: string
  phone?: string
  userImage?: string
  profileImage?: string
  address?: string
  userType?: string
  status: string
}

interface INewUser extends IUser {
  userId: number
}
```

2023-06-13 10:45 UTC, Mu7ammadAbed commented on src/controllers/auth/signup.ts
> +    }
This query should be moved to queries folder

2023-06-13 10:45 UTC, Mu7ammadAbed commented on src/queries/user/signup.ts
> +}: CreateUserProps): Promise<IUser> => {
```suggestion
}: CreateUserProps): Promise<INewUser > => {
```

2023-06-13 10:45 UTC, Mu7ammadAbed commented on src/controllers/auth/signup.ts
> +    })
```suggestion
res.cookie('token', token, { httpOnly: true, secure: process.env.NODE_ENV === 'production' })
      .json({
        message: 'User Created Successfully',
        data: {
          fullName,
          email: newUser.email,
          phone: newUser.phone,
          userImage,
          profileImage,
          address,
          userType,
          status
        }
      })
```

2023-06-13 11:10 UTC, Mu7ammadAbed requested changes

2023-06-13 11:10 UTC, Mu7ammadAbed commented on src/interfaces/models.ts
> +  userType: string
```suggestion
  userType?: string
```

2023-06-13 12:59 UTC, Mu7ammadAbed commented on src/controllers/auth/signup.ts
> +    })
@AbdallahAbujazar You forgot this one

2023-06-14 07:22 UTC, Mu7ammadAbed approved these changes

2023-06-14 07:24 UTC, MohammedSallout approved these changes

2023-06-14 07:25 UTC, Mu7ammadAbed approved these changes

2023-06-14 07:25 UTC, haitham-akram approved these changes

2023-06-14 07:26 UTC, merged