17 handle login
GSG-G13/Petopia pull request #26
Opened 2023-06-13 13:04 UTC by MohammedSallout

2023-06-13 20:20 UTC, haitham-akram commented on jest.config.js
> +module.exports = {
export { preset: 'ts-jest',
  transform: {
    '^.+\\.(ts|tsx)?$': 'ts-jest',
    '^.+\\.(js|jsx)$': 'babel-jest',
  },}

2023-06-13 20:34 UTC, haitham-akram approved these changes

2023-06-13 20:34 UTC, MohammedSallout commented on jest.config.js
> +module.exports = {
Done

2023-06-14 07:54 UTC, Mu7ammadAbed requested changes

2023-06-14 08:02 UTC, Mu7ammadAbed commented
@MohammedSallout Resolve conflicts

2023-06-14 09:09 UTC, Mu7ammadAbed requested changes

2023-06-14 09:09 UTC, Mu7ammadAbed commented on src/validation/auth/login.ts
> +  password: string().min(5).required()
```suggestion
  password: string().min(8).required()
```

2023-06-14 09:09 UTC, Mu7ammadAbed commented on src/controllers/auth/login.ts
> +        res.cookie('token', token).json({ message: 'Login successfully' })
```suggestion
        res.cookie('token', token, { httpOnly: true, secure: process.env.NODE_ENV === 'production' })
        .json({ message: 'Login successfully' })
```

2023-06-14 09:09 UTC, Mu7ammadAbed commented on src/controllers/auth/login.ts
> +      const result = await bcrypt.compare(password, hashedPassword)
```suggestion
      const isPasswordTrue = await bcrypt.compare(password, hashedPassword)
```

2023-06-14 09:09 UTC, Mu7ammadAbed commented on src/queries/auth/login.ts
> +export default loginQuery
```suggestion
import User from '../../models/User'
import { type IUser } from '../../interfaces/models'

const loginQuery = async (userData: { email: string }): Promise<IUser | null> => {
  const { email } = userData

  const user = await User.findOne({
    where: {
      email
    }
  })

  return user
}

export default loginQuery
```

2023-06-14 09:38 UTC, Mu7ammadAbed approved these changes

2023-06-14 09:51 UTC, AbdallahAbujazar approved these changes

2023-06-14 09:52 UTC, merged