back end comment routre
GSG-G13/Petopia pull request #37
Opened 2023-06-16 13:04 UTC by MohammedSallout

- GET all comments
- POST new comment
- GET comment by id
- PUT to update comment

2023-06-17 14:53 UTC, Mu7ammadAbed requested changes

2023-06-17 14:53 UTC, Mu7ammadAbed commented on src/controllers/comment/deleteComment.ts
> +    const { commentId } = req.params
Where's the validation for this?

2023-06-17 14:53 UTC, Mu7ammadAbed commented on src/controllers/comment/getComments.ts
> +  const postId = req.params.postId
```suggestion
  const { postId } = req.params
```

2023-06-17 15:41 UTC, Mu7ammadAbed requested changes

2023-06-17 15:41 UTC, Mu7ammadAbed commented on src/routes/index.ts
> +router.use(commentRouter)
```suggestion
router.use('/comments', commentRouter)
```

2023-06-17 15:58 UTC, Mu7ammadAbed commented on src/routes/comment.ts
> +commentRouter.get('/post/:postId/comments', getComments)
this shouldn't be here

2023-06-18 13:26 UTC, Mu7ammadAbed approved these changes

2023-06-18 13:30 UTC, AbdallahAbujazar approved these changes

2023-06-18 13:30 UTC, haitham-akram approved these changes

2023-06-18 13:31 UTC, merged